# Generated by Django 5.0.4 on 2024-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='id_aluno',
            field=models.IntegerField(default=0),
        ),
    ]
