# Generated by Django 5.0.4 on 2024-05-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_materia_id_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='id_aluno',
            new_name='nome_aluno',
        ),
    ]
