# Generated by Django 5.0.4 on 2024-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_id_aluno_materia_nome_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nome_aluno',
            field=models.CharField(max_length=120),
        ),
    ]
