# Generated by Django 5.0.4 on 2024-05-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_materia_nome_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='materias',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nome_aluno',
        ),
        migrations.AddField(
            model_name='materia',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
    ]
