# Generated by Django 5.0.4 on 2024-05-22 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_serieturma_remove_aluno_serie_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='serie_turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.serieturma'),
            preserve_default=False,
        ),
    ]
