# Generated by Django 5.0.4 on 2024-05-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aluno_serie_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serieturma',
            old_name='serie_turma',
            new_name='nome_turma',
        ),
    ]
